### ISSUE TITLE
Tugas1

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2104#1]

**Comment by najliaintani** [comment]
COMPUTATIONAL THINGKING KELOMPOK 1
- Najlia Intani 2C2230010
- Ariela Safmi Ramdani 2C2230005
- Aji Sakti Saputra
- Yusuf Sohibul Fallah 2C2230013
https://github.com/najliaa/Pemrograman-Lanjut/blob/main/COMPUTATIONAL%20THINGKING%20KEL%201.pdf

**Comment by KanayaDzikra** [comment]
Computional Thinking kelompok 4

Reva Anwar 2C2230002
Fitri Fatimah 2C2230003
Kanaya Dzikra Setiadi 2C2230015
Amelia Regina Permana 2C2230019

https://github.com/KanayaDzikra/pemograman-lanjutan/blob/main/problem%20statement%20pempro%20kel%204.pdf

**Comment by nadinevaliaa** [comment]
Computational Thinking Kelompok 2

Nadine Valia Azzahra 2C2230007
Rafid Farhan Zai 2C2230001
Riyan Putra Pratama 2C2230016
Muhammad Musa Ibrahim 2C2230002

https://github.com/nadinevaliaa/SD2104/blob/main/Tugas%20Pertemuan%201%20Nadine%20Valia%202C2230007.pdf

https://github.com/nadinevaliaa/SD2104/blob/main/Tugas%20pertemuan%201%20(flowchart%20generalisasi).pdf

**Comment by fadhlijahfal1** [comment]
Computational Thinking Kelompok 3

NAMA ANGGOTA :
- Ahmad Muwafiqul ’Adli (2C2230006)
- Fadhli Jahfal Aufa Maulana (2C2230008)
- Rizwar Syefulloh (2C2230009)
- Budi Kurnia (2C2230018)

Link : https://github.com/fadhlijahfal1/SD2104-Pemrograman-Lanjut-/tree/c5288273a8d0fcc9903d546fb0a1c4dd47989fb1/Tugas%201%20Pemrograman%20Lanjut%20(Computational%20Thinking)
