### ISSUE TITLE
Tugas2

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD2104#2]

**Comment by najliaa** [comment]
[Uploading H01_2C2230010_01_NAJLIAINTANI.zip…]()
Najlia Intani_2C2230010

**Comment by najliaintani** [comment]
https://github.com/najliaa/Pemrograman-Lanjut/blob/main/H01_2C2230010_01_NAJLIAINTANI.zip
Najlia Intani 2C2230010

**Comment by ryynnptr** [comment]
Riyan putra pratama - 2C2230016

https://github.com/ryynnptr/pemrograman_lanjut/blob/ece817041f84d1eefc27bc2b57f2ee772dd12141/H01_2C2230016_01_RIYAN%20PUTRA%20PRATAMA.zip

**Comment by ajisakti554** [comment]
Aji sakti Saputra - 2C2230012
https://github.com/ajisakti554/Tugas-Alpro/blob/main/python.zip

**Comment by AmeliaReginaa** [comment]
Amelia Regina Permana - 2C2230019 
https://github.com/AmeliaReginaa/pemograman-lanjutan/blob/main/H01_2C2230019_01_AmeliaReginaP.zip

**Comment by nadinevaliaa** [comment]
Nadine Valia Azzahra - 2C2230007
https://github.com/nadinevaliaa/SD2104/blob/main/H01_2C2230007_NADINEVALIA.zip

**Comment by fadhlijahfal1** [comment]
Nama : Fadhli Jahfal Aufa Maulana
NRP : 2C2230008

Link : https://github.com/fadhlijahfal1/SD2104-Pemrograman-Lanjut-/tree/dd87bc5f14a72e72164d966592bb2aaa4de19f40/H0_2C2230008_FADHLI%20JAHFAL

**Comment by revaanwarr** [comment]
Reva Anwar - 2C2230003
https://github.com/revaanwarr/pemrograman-lanjut/tree/main/post%20test%20%231

**Comment by ApikMu** [comment]
https://github.com/ApikMu/Ahmad/blob/main/pytthon.zip


nama : Ahmad muwafiqul 'adli
NRP : 2c2230006

**Comment by KanayaDzikra** [comment]
Kanaya Dzikra Setiadi - 2C2230015
https://github.com/KanayaDzikra/pemograman-lanjutan/blob/main/H01_2C2230015_KANAYADZIKRA.zip

**Comment by FitriFatimah6** [comment]
Fitri Fatimah 2C2230004

https://github.com/FitriFatimah6/pemograman-lanjutan-sem3/blob/2284e03c465a6d388c7d6a496eb521d3cbb93189/H01_2C2230004_FITRI%20FATIMAH.zip

**Comment by rafaza24** [comment]
Rafid Farhan Zai 2C2230001
https://github.com/rafaza24/SD2104/blob/main/tugas/H01_2C2230001_01.zip

**Comment by ArielaSafra** [comment]
Ariela Safmi Ramdhani - 2C2230005 
https://github.com/ArielaSafra/Pemrograman-lanjut-2D2104-/blob/main/H01_2C2230005_01_ARIELA%20SAFMI.zip

**Comment by yusufsf01** [comment]
Yusuf Sohibul Falah
2C2230013
https://github.com/yusufsf01/Pemrograman-Lanjut/tree/main/Tugas%20Pemrograman

**Comment by Rizwar11** [comment]
https://github.com/Rizwar11/TugasAlpro/blob/main/Pemro%20rizwar%20smt%202%20(2).zip
Rizwar Syaefulloh
2C2230009

**Comment by Budikurnia26** [comment]
https://github.com/Budikurnia26/SD2104

Budi Kurnia 2C2230018
